when:
  - event: push
steps:
  - name: test
    image: nixos/nix
    environment:
      ATTIC_TOKEN:
        from_secret: attic_token
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - echo 'extra-substituters = https://cache.bas.es/bases' >> /etc/nix/nix.conf
      - echo 'extra-trusted-public-keys =  bases:bg7mtzwSME8dI+IXhYLzDTQ4TzY4zMmIzyeqjgR5Isg=' >> /etc/nix/nix.conf
      - nix profile add nixpkgs#attic-client
      - attic login local https://cache.bas.es/ $ATTIC_TOKEN
      - attic use bases
      - nix develop --command bash -c "testament all"
      - nix build .
      - attic push bases ./result
    volumes:
      - /nix
