when:
  - event: push
steps:
  - name: rebuild
    image: nixos/nix
    environment:
      ATTIC_TOKEN:
        from_secret: attic_token
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix profile add nixpkgs#attic-client
      - attic login local https://cache.bas.es/ $ATTIC_TOKEN
      - attic use bases
      - nix build .
      - attic push bases ./result
    volumes:
      - /nix
